name: 构建APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 最关键：直接用系统默认路径生成，100%不报错
      - name: 创建 .android 文件夹并生成调试签名
        run: |
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore \
          -alias androiddebugkey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass android \
          -keypass android \
          -dname "CN=Android Debug,O=Android,C=US"
# 🔥 对应生成 key.properties（严格匹配）
      - name: 创建 key.properties
        run: |
          echo "storePassword=possystem" > android/key.properties
          echo "keyPassword=possystem" >> android/key.properties
          echo "keyAlias=possystem" >> android/key.properties
          echo "storeFile=my-jks.jks" >> android/key.properties


      # 🔥 生成合法 google-services.json
      - name: 生成 google-services.json
        run: |
          cat > android/app/google-services.json << EOF
          {
            "project_info": {
              "project_number": "123456789",
              "project_id": "fake-project",
              "storage_bucket": "fake.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:abcdef",
                  "android_client_info": {
                    "package_name": "com.evanlu.possystem"
                  }
                },
                "api_key": [{"current_key": "fake_key"}]
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: 安装Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.x'
          channel: stable

      - name: 安装依赖
        run: flutter pub get

      # 🔥 【官方标准打包】绝对不闪退
      - name: 打包APK
        run: flutter build apk --debug

      # 上传
      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/
