name: Tests

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "scripts/**"
      - "mkdocs.yaml"
      - "Makefile"

  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  code-checking:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.x"
          cache: true
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Linter
        run: flutter analyze .

      - name: Format
        run: dart format --set-exit-if-changed --show none --line-length 120 .
